services:
  front:
    build:
      context: ./DuramatFront
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped

  backend:
    build:
      context: ./DuramatBack
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: "1"